image: alpine:edge

before_script:
  - '.gitlab-ci/prep-env'

  # Install openssh-client if ssh-agent is unavailable
  - which ssh-agent || (apk add --no-cache openssh-client)

  # Run ssh-agent inside build environment
  - eval $(ssh-agent -s)

  # Add the SSH key for rsyncing
  - echo "$SSH_PRIVATE_KEY" | ssh-add -

  # Disable host key checking, because that's smart
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

after_script:
  - rm -f /etc/pkey/*

stages:
  - build

build_and_deploy:
  stage: build
  only:
    - master
  script:
    - '.gitlab-ci/download'
    - '.gitlab-ci/build-pkgs'
    - '.gitlab-ci/upload'
  #cache:
    #key: "$CI_BUILD_REF_NAME"
    #paths:
      #- packages/

test_build:
  stage: build
  except:
    - master
  script:
    - '.gitlab-ci/download'
    - '.gitlab-ci/build-pkgs'
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
      - packages/
